### ISSUE TITLE
Size sorunu

### ISSUE THREAD

**Issue by maqtay** [emreesen27/Android-Nested-Progress#2]
Width ve height'i manuel olarak verince progress kayboluyor. Size eklenebilir. Teşekkürler

**Comment by emreesen27** [comment]
Hi Murat :)

It is necessary to set the width and height values ​​​​to be square.

```xml 
    <com.sn.lib.NestedProgress
        android:id="@+id/pb1"
        android:layout_width="120dp"
        android:layout_height="120dp"/>

    <com.sn.lib.NestedProgress
        android:id="@+id/pb2"
        android:layout_width="80dp"
        android:layout_height="80dp"/>
```

<img width="382" alt="Screen Shot 2022-05-22 at 17 58 03" src="https://user-images.githubusercontent.com/45034416/169701792-5b0ebafc-5c38-4f04-b854-26d41a325863.png">

**Comment by maqtay** [comment]
When I set the width and height to 24 dp, the progress disappears. I guess there is a limit

**Comment by emreesen27** [comment]
Library can't draw that accurately. This is too small a value to draw nested circles. You can review [here](https://github.com/emreesen27/Android-Nested-Progress/blob/master/lib/src/main/java/com/sn/lib/NestedProgress.kt#L203), if you find a solution, open a pr.

**Comment by maqtay** [comment]
thanks for the answers. maybe i'll try to find a solution later
